# Generated by Django 6.1.1 on 2026-09-30 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'permissions': [('download_qgis', 'Can download the QGIS project and auth file')],
            },
        ),
    ]
